//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SOPAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh shoot
        ///Shucks
        ///Da&apos;gum
        ///D&apos;oh
        ///Aww, tartar sauce
        ///Ouch
        ///Well that&apos;s not right
        ///Ya dun goof&apos;d
        ///It won&apos;t let me
        ///Houston, we have a problem
        ///A thing happened
        ///Oye, tenemos una problema
        ///Not again!
        ///You&apos;ve gotta be kidding me
        ///What&apos;d you do that for?
        ///I trusted you!
        ///Nope.avi
        ///Well, at least I tried
        ///Danger, Will Robinson
        ///I hate it when that happens
        ///OHHHHH NOOOOOOO!
        ///Where&apos;s the N-1?
        ///Hey, who turned out the lights?
        ///Help me, Obi-Wan Kenobi, you&apos;re my only hope
        ///Doctor, we&apos;re losing him!
        ///*Sigh* I&apos;ll go get [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Openers {
            get {
                return ResourceManager.GetString("Openers", resourceCulture);
            }
        }
    }
}
